language: node_js
node_js:
  - 0.8

script: xvfb-run -a testem ci

branches:
  only:
    - master

before_install:
  - npm install -g testem

notifications:
  webhooks:
    urls:
      - http://webhooks.nodejitsu.com/1/deploy
    on_success: always
    on_failure: never
  email:
    recipients:
      - jedahu@gmail.com
    on_success: [change]
    on_failure: [always]
