language: node_js
node_js:
  - 0.8

branches:
  only:
    - master

before_install:
  - "export DISPLAY=:99"
  - "sh -e /etc/init.d/xvfb start"

notifications:
  email:
    recipients:
      - jedahu@gmail.com
    on_success: [change]
    on_failure: [always]
