#!/bin/sh

run_build() {
  rm -rf dist
  mkdir dist

  cp -R \
    www/docs.html \
    www/worker \
    www/css/*.png \
    www/css/*.gif \
    www/package.json \
    dist

  traceurc \
    --inline-modules \
    --source-maps \
    --freeVariableChecker=false \
    --trapMemberLookup=false \
    www/js/app/start_$1.js


  cat \
    www/css/jquery-ui/jquery-ui-1.9.2.custom.css \
    www/css/angular-ui.css \
    www/css/select2.css \
    >dist/main.css

  stylus -u nib -c \
    <www/css/browse.styl \
    >>dist/main.css

  cat \
    www/js/lib/jquery.js \
    www/js/lib/jquery-ui.js \
    www/js/lib/select2.js \
    www/js/lib/angular.js \
    www/js/lib/angular-sanitize.js \
    www/js/lib/angular-ui.js \
    www/js/lib/js-yaml.js \
    www/js/lib/runtime.js \
    out/www/js/app/start_$1.compiled.js \
    >dist/main.js

  cp out/www/js/app/start_$1.map dist/main.map
}

START=nw

while [ "$1" ]; do
  case "$1" in
    -w)
      WATCH=1
      ;;
    nw)
      START=nw
      ;;
    web)
      START=browser
      ;;
  esac
  shift
done

if [ $WATCH ] && which inotifywait; then
  run_build $START
  while inotifywait -r -e modify -e create -e delete www; do run_build $START; done
else
  run_build $START
fi
