#!/bin/bash

# set -x
set -e
set -o pipefail

BRANCH=`git symbolic-ref HEAD --short`
if [ "$BRANCH" = 'master' ]; then
  VERSION=`node -e 'process.stdout.write(require("./package.json").version)'`
  git tag "$VERSION" -m"version $VERSION" || echo 'WARNING: Tagging failed.'
fi
