#!/bin/bash

# set -x
set -e
set -o pipefail

BRANCH=`git symbolic-ref HEAD --short`
if [ "$BRANCH" = 'master' ]; then
  npm shrinkwrap
  grunt bump:patch
  git add npm-shrinkwrap.json package.json
fi
